name: 'Checkout Buildx'
description: 'Checks out the repository and configures Docker Buildx with QEMU and logs in to DockerHub'
author: 'JonasAlfredsson'
branding:
  icon: 'life-buoy'
  color: 'blue'

inputs:
  should_login:
    description: 'Boolean stating if we should login to DockerHub or not'
    required: false
    default: true
  username:
    description: 'Username used to login to DockerHub'
    required: false
  password:
    description: 'Password or personal access token used to login to DockerHub'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.4.0

    - name: Set up QEMU environment
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Login to DockerHub
      if: ${{ inputs.should_login }}
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
